### PR TITLE
Fixed syntax error in index.js

### PR DESCRIPTION
**Pull request by benvan**
Added missing parenthesis in index.js.

Given the code currently doesn't transpile... are you using something else instead of this project? If so, care to share?

### CODE REVIEW

**Comment by kubante** [comment]
try using https://github.com/STRML/react-grid-layout

**Comment by kubante** [comment]
I am still trying to implement the react-grid-layout in my project, wikiver.se. Stopped where I needed to dynamically adjust the size of the bricks..  Unfortunately I only have very little spare time...

**Comment by benvan** [comment]
Thanks - funnily enough I used react-grid-layout originally, and tried switching to this after realising that it didn't play nicely with realtime components whilst dragging.

**Comment by kubante** [comment]
what do you mean by realtime components?  

packery and draggabilly are great when you manipulate the dom directly. My experience was that with react the overhead to make it work properly (especially the cat-dog-dilemma with componenDidUpdate that you get if you need to dynamically add/remove packery-elements) was too much headache to keep seizing it. But I might obviously be wrong.  For what project do you need this?  have a good day

**Comment by benvan** [comment]
I'm building a dashboard that helps to debug arduino projects. Some of the components in the dashboard will update (visually) at around 60hz, with realtime values from the arduino There's a bug in react-grid-layout where, if any component updates _whilst_ you're dragging any other component, the drag target resets momentarily and then snaps back. This results in some fairly awkward UX (very difficult to drag things reliably).

Bizarrely.. I spent this morning 'fixing' the react-grid-layout bug, only to discover that the bug completely disappears if you use 'inline' grid layout mode. That is - instead of passing `layout={layout}` to the container, you pass `_grid={{ x:1, y:2 ...etc}}` to each child. This makes for a much simpler solution - I'll revise my solution and create a PR possibly later on today.

**Pull request merged**
